import os


class Config:
     FLASK_APP = os.getenv('FLASK_APP')
     FLASK_ENV = os.getenv('FLASK_ENV')
     FLASK_DEBUG = os.getenv('FLASK_DEBUG')
     FLASK_RUN_PORT = os.getenv(' FLASK_RUN_PORT')
     FLASK_RUN_HOST = os.getenv('FLASK_RUN_HOST')
     SQLALCHEMY_DATABASE_URI = os.getenv('SQLALCHEMY_DATABASE_URI')
     SECRET_KEY = os.getenv('SECRET_KEY')
     JWT_COOKIE_SECURE = os.getenv('JWT_COOKIE_SECURE')
     JWT_TOKEN_LOCATION = os.getenv('JWT_TOKEN_LOCATION')
     SWAGGER_UI_REQUEST_DURATION = os.getenv('SWAGGER_UI_REQUEST_DURATION')
     SWAGGER_UI_DOC_EXPANSION = os.getenv("SWAGGER_UI_DOC_EXPANSION")
     SQLALCHEMY_TRACK_MODIFICATIONS = os.getenv('SQLALCHEMY_TRACK_MODIFICATIONS')
     JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY')
     CACHE_TYPE = os.getenv('CACHE_TYPE')
     CACHE_DEFAULT_TIMEOUT = os.getenv('CACHE_DEFAULT_TIMEOUT')
     CACHE_REDIS_HOST = os.getenv('CACHE_REDIS_HOST')
     CACHE_REDIS_PORT = os.getenv('CACHE_REDIS_PORT')
     CACHE_REDIS_DB = os.getenv('CACHE_REDIS_DB')
     CACHE_REDIS_URL = os.getenv('CACHE_REDIS_URL')
