version: '3.8'

services:
  db:
    image: postgis/postgis
    container_name: 'navi_backend_postgres'
    hostname: 'db'
    ports:
      - '127.0.0.1:5432:5432'
    env_file:
      env/db.secret.env
    volumes:
      - navi_backend_db_data_dev:/var/lib/postgresql/data


  redis:
    image: library/redis:6
    container_name: 'navi_backend_redis'
    hostname: 'redis'
    ports:
      - '127.0.0.1:6379:6379'

volumes:
  navi_backend_db_data_dev: